### PR TITLE
Update 3.1.0

### PR DESCRIPTION
**Pull request by JennaLipscomb**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JennaLipscomb** [comment]
@conda-forge-admin, please rerender

**Comment by JennaLipscomb** [comment]
@sodre You're listed as a maintainer, but it didn't tag you for some reason. Can you review?

**Comment by JennaLipscomb** [comment]
@conda-forge/core can someone review this? There's only one maintainer listed

**Comment by beckermr** [comment]
Please make a PR to add yourself as a maintainer per this command: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

Then you will be able to merge this PR.

**Comment by JennaLipscomb** [comment]
@conda-forge-admin, please update team

**Comment by beckermr** [comment]
you need to add yourself to the feedstock before the update team command will work - use the command I linked above and put that in a new issue in the title

**Comment by JennaLipscomb** [comment]
@conda-forge-admin, please add user @JennaLipscomb

**Comment by beckermr** [comment]
> use the command I linked above and put that in a new issue in the title

see this please

**Comment by beckermr** [comment]
see here: https://github.com/conda-forge/spacy-model-fr-feedstock/issues/7

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
merge when you are happy with it!

**Comment by JennaLipscomb** [comment]
@beckermr sorry for my confusion and thanks for your help! I'll go ahead and do the same for the other two spacy repos with the same maintainer.

**Pull request merged**
